version: '3.9'
services:
  weather-api:
    image: weather-api
    container_name: weather-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - server-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${SERVER_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - server-network

volumes:
  postgres_data:

networks:
  server-network:
